server:
  port: 8899

spring:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password: 123456
#    pool:
#      #最大连接数
#      max-active: 8
#      #连接等待时间
#      max-wait: -1
#      #最大空闲连接
#      max-idle: 8
#      #最小空闲连接
#      min-idle: 0
#    timeout: 30000

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://rm-2zep2q5s0qkf2234m.mysql.rds.aliyuncs.com:3306/jpay?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
#    username: jpay_rw
#    password: 1OEQzX%3W*l1
#
#
#redis:
#  # redis数据库索引(默认为0)，我们使用索引为3的数据库，避免和其他数据库冲突
#  database: 3
#  # redis服务器地址（默认为loaclhost）
#  host: 127.0.0.1
#  # redis端口（默认为6379）
#  post: 6379
#  # redis访问密码（默认为空）
#  password: 123456
#  # redis连接超时时间（单位毫秒）
#  timeout: 0
#  # redis连接池配置
#  pool:
#    # 最大可用连接数（默认为8，负数表示无限）
#    max-active: 8
#    # 最大空闲连接数（默认为8，负数表示无限）
#    max-idle: 8
#    # 最小空闲连接数（默认为0，该值只有为正数才有用）
#    min-idle: 0
#    # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
#    max-wait: -1

jedis :
  pool :
    host : 127.0.0.1
    port : 6379
    database: 3
    password: 123456
    config :
      maxTotal: 100
      maxIdle: 10
      maxWaitMillis : 100000



mybatis:
  mapper-locations: classpath:mapper/*.xml
